from EjemploMatrices import *

if __name__ == '__main__':
    # Ejemplo()
    # Unos()
    # Ceros()
    # Random()
    # Vacia()
    # Full()
    # Espaciado()
    # MatrizIdentidad()
    # InspeccionMatrices()
    # TipoDatoMatriz()
    # TamanoForma()
    # CambioForma()
    # SeleccionElemento()
    # ValorMax()
    # ValorMin()
    # ValorSuma()
    # RaizCuadradaMatriz()
    # SumaMatriz()
    # RestaMatriz()
    # MultiplicacionMatriz()
    # DivisionMatriz()
    # MatrizAleatoria()
    # Ejercicio1Resuelto()
    # ExtraerValorMatriz()
    Ejercicio2()
